version: '3'
services:
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
      dockerfile: Dockerfile
    image: udagram-api-feed:latest

  udagram-api-user:
    build:
      context: ./udagram-api-user
      dockerfile: Dockerfile
    image: udagram-api-user:latest

  frontend:
    build:
      context: ./udagram-frontend
      dockerfile: Dockerfile
    image: udagram-frontend:local

  reverseproxy:
    build:
      context: ./udagram-reverseproxy
      dockerfile: Dockerfile
    image: reverseproxy:latest
