version: '3'
services:
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:latest

  udagram-api-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:latest

  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local

  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:latest
